import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import 'nouislider/dist/nouislider.css';
import 'suggestions-jquery/dist/css/suggestions.min.css';
// import 'swiper/swiper-bundle.css';

import "./style/blocks/wpcf7.scss";
import "./style/blocks/btn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/counter.scss";
import "./style/blocks/input.scss";
import "./style/blocks/select.scss";
import "./style/blocks/slider.scss";
import "./style/blocks/file.scss";
import "./style/blocks/tabs.scss";
import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

import './modules/header/header.scss';
import './modules/footer/footer.scss';
import './modules/breadcrumbs/breadcrumbs.scss';
import './modules/form/form.scss';
import './modules/popup/popup.scss';
import './modules/frontSlider/frontSlider.scss';
import './modules/welcomeText/welcomeText.scss';
// import './modules/alphabetCatalog/alphabetCatalog.scss';
import './modules/constructor/constructor.scss';
import './modules/brandsGrid/brandsGrid.scss';
import './modules/servicesSlider/servicesSlider.scss';
import './modules/photos/photos.scss';
import './modules/testimonialsSlider/testimonialsSlider.scss';
import './modules/orderMarquee/orderMarquee.scss';
import './modules/question/question.scss';
import './modules/footerMenu/footerMenu.scss';
import './modules/head/head.scss';
import './modules/brandsList/brandsList.scss';
import './modules/seoText/seoText.scss';
import './modules/modelsList/modelsList.scss';
import './modules/contacts/contacts.scss';
import './modules/newsList/newsList.scss';
import './modules/news/news.scss';
import './modules/testimonials/testimonials.scss';
import './modules/product/product.scss';
import './modules/productGallery/productGallery.scss';
import './modules/productInfo/productInfo.scss';
import './modules/productTestimonials/productTestimonials.scss';
import './modules/productConstructor/productConstructor.scss';
import './modules/cart/cart.scss';
import './modules/about/about.scss';
import './modules/citySelect/citySelect.scss';
