import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import 'nouislider/dist/nouislider.css';
// import 'swiper/swiper-bundle.css';

import "./style/blocks/wpcf7.scss";
import "./style/blocks/btn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/input.scss";
import "./style/blocks/select.scss";
import "./style/blocks/slider.scss";
import "./style/blocks/file.scss";
import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

import './modules/photoswipe/photoswipe.scss';
import './modules/photoswipe/default-skin.scss';

import './modules/header/header.scss';
import './modules/footer/footer.scss';
import './modules/form/form.scss';
import './modules/popup/popup.scss';
import './modules/frontSlider/frontSlider.scss';
import './modules/welcomeText/welcomeText.scss';
import './modules/alphabetCatalog/alphabetCatalog.scss';
import './modules/constructor/constructor.scss';
import './modules/brandsGrid/brandsGrid.scss';
import './modules/servicesSlider/servicesSlider.scss';
import './modules/gallery/gallery.scss';
import './modules/testimonialsSlider/testimonialsSlider.scss';
import './modules/orderMarquee/orderMarquee.scss';
import './modules/question/question.scss';
import './modules/footerMenu/footerMenu.scss';
import './modules/head/head.scss';
import './modules/brandsList/brandsList.scss';
import './modules/seoText/seoText.scss';
import './modules/modelsList/modelsList.scss';
import './modules/contacts/contacts.scss';
import './modules/newsList/newsList.scss';
import './modules/news/news.scss';
import './modules/testimonials/testimonials.scss';
